name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    container:
      image: redhat/ubi9:latest
      options: --privileged --volume /:/run/host:rw --volume /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Install Podman
        run: |
          dnf install -y podman

      - name: Reclaim Disk Space
        run: |
          podman run --rm --privileged --volume /run/host:/run/host:rw docker.io/library/ubuntu:24.04 bash -c "apt -o RootDir=/run/host remove -y '^mysql-.*'"

          rm -rf "/run/host/usr/local/lib/android"
          rm -rf "/run/host/usr/share/dotnet"
