name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    container:
      image: redhat/ubi9:latest
      options: --privileged --volume /:/run/host:rw --volume /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Install Podman
        run: |
          dnf install -y podman

      - name: Reclaim Disk Space
        run: |
          podman run --rm --privileged \
            --volume /run/host:/run/host:rw \
            --volume /run/host/etc/apt:/etc/apt:rw \
            --volume /run/host/usr/lib/apt:/usr/lib/apt:rw \
            --volume /run/host/var/cache:/var/cache:rw \
            --volume /run/host/var/lib/dpkg:/var/lib/dpkg:rw \
            --volume /run/host/var/lib/apt/lists/partial:/var/lib/apt/lists/partial:rw \
            --volume /run/host/var/cache/apt/archives/partial:/var/cache/apt/archives/partial:rw \
            --volume /run/host/var/lib/dpkg/status:/var/lib/dpkg/status:rw \
            docker.io/library/ubuntu:24.04 bash -c "echo N | sudo tee /sys/module/overlay/parameters/metacopy; apt -o Dir=/run/host remove -y '^mysql-.*'"

          rm -rf "/run/host/usr/local/lib/android"
          rm -rf "/run/host/usr/share/dotnet"
